name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install chdb library
      run: curl -sL https://lib.chdb.io | bash
    - name: Copy chdb lib to root path
      run: cp /usr/local/lib/libchdb.so .
    - name: Compile native extension
      run: |
        bundle exec rake compile
        bundle exec rake build
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        bundle exec rake spec
